### ISSUE TITLE
tendril v0.4.1 error[E0793]: reference to packed field is unaligned

### ISSUE THREAD

**Issue by ghost** [kmcallister/tendril#73]
```
remote: Compiling tendril v0.4.1
remote: error[E0793]: reference to packed field is unaligned
remote: --> /tmp/codon/tmp/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/tendril-0.4.1/src/tendril.rs:241:20
remote: |
remote: 241 | if (*header).refcount.decrement() == 1 {
remote: | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote: |
remote: = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
remote: = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
remote: = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use read_unaligned/write_unaligned (loads and stores via *p must be properly aligned even when using raw pointers)
remote:
remote: error[E0793]: reference to packed field is unaligned
remote: --> /tmp/codon/tmp/cache/cargo/registry/src/index.crates.io-6f17d22bba15001f/tendril-0.4.1/src/tendril.rs:958:9
remote: |
remote: 958 | (*self.header()).refcount.increment();
remote: | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote: |
remote: = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
remote: = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
remote: = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use read_unaligned/write_unaligned (loads and stores via *p must be properly aligned even when using raw pointers)
remote:
remote: For more information about this error, try rustc --explain E0793.
remote: error: could not compile tendril (lib) due to 2 previous errors
remote: warning: build failed, waiting for other jobs to finish...
remote: could not compile dependency :meeseeks_html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile meeseeks_html5ever", update it with "mix deps.update meeseeks_html5ever" or clean it with "mix deps.clean meeseeks_html5ever"
remote: ** (RuntimeError) Rust NIF compile error (rustc exit code 101)
remote: lib/mix/tasks/compile.rustler.ex:67: Mix.Tasks.Compile.Rustler.compile_crate/1
remote: (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
remote: lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
remote: (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
remote: (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
remote: (mix) lib/mix/tasks/compile.all.ex:52: Mix.Tasks.Compile.All.do_compile/4
remote: (mix) lib/mix/tasks/compile.all.ex:23: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
remote: (mix) lib/mix/tasks/compile.all.ex:39: Mix.Tasks.Compile.All.with_logger_app/1
```

Just happened on heroku without any updates or changes

**Comment by jdm** [comment]
I believe this is fixed if you updated to the latest version (0.4.3).
